# Generated by Django 5.0.6 on 2024-05-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aolswebapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Privacy_Policy',
            new_name='PrivacyPolicy',
        ),
        migrations.RenameModel(
            old_name='Terms_of_Service',
            new_name='TermsOfService',
        ),
        migrations.RenameField(
            model_name='privacypolicy',
            old_name='privacy_policy_pdf_file',
            new_name='pdf_file',
        ),
        migrations.RenameField(
            model_name='termsofservice',
            old_name='terms_of_service_pdf_file',
            new_name='pdf_file',
        ),
    ]
